#!/bin/bash
# set -e
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_USER: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_USER"
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_HOST: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_HOST"
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_GMAIL_APP_USERNAME: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_GMAIL_APP_USERNAME"

mkdir -p ~/.ssh
chmod 700 ~/.ssh
printf '%s\n' "$USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_RSA_PRIVATE" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
printf '%s\n' "$USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_RSA_PUBLIC" > ~/.ssh/id_rsa.pub
chmod 600 ~/.ssh/id_rsa.pub
touch ~/.ssh/config
cat <<EOF > ~/.ssh/config
Host prod
	HostName ${USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_HOST}
	User ${USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_USER}
	IdentityFile ~/.ssh/id_rsa
	IdentitiesOnly yes
EOF
chmod 600 ~/.ssh/config

