#!/bin/bash
# set -e
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_USER: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_USER"
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_HOST: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_HOST"
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_RSA_PRIVATE: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_RSA_PRIVATE"
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_RSA_PUBLIC: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_RSA_PUBLIC"
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_GMAIL_APP_USERNAME: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_GMAIL_APP_USERNAME"
echo "ENV - USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_GMAIL_APP_PASSWORD: $USER_CODESPACE_PROTONMAILEXPORT_ENV_PRODUCTION_GMAIL_APP_PASSWORD"





# mkdir -p ~/.ssh
# chmod 700 ~/.ssh
# printf '%s\n' "$SECRET_SSH_CONFIG_ID_RSA" > ~/.ssh/id_rsa
# chmod 600 ~/.ssh/id_rsa
# cp /workspace/.devcontainer/codespaces-export-to-gmail/ssh_config ~/.ssh/config
# chmod 600 ~/.ssh/config
