services:

    proton-mail-export-to-gmail:
      image: ghcr.io/sigmalko/proton-mail-export-to-gmail:${IMG_VERSION_PROTON_MAIL_EXPORT_TO_GMAIL}
      restart: unless-stopped   
      environment:
        SERVER_PORT: 8080
      ports:
        - 8080:8080

