FROM openjdk:21-slim
ARG DOCKER_TAG_VERSION
ARG GITHUB_RUN_NUMBER
ENV DOCKER_TAG_VERSION ${DOCKER_TAG_VERSION}
ENV GITHUB_RUN_NUMBER ${GITHUB_RUN_NUMBER}
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends locales curl \
    && rm -rf /var/lib/apt/lists/*
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
RUN locale
WORKDIR /workspace
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

VOLUME /workspace/.data/h2-database
VOLUME /workspace/.data/proton-emls
VOLUME /workspace/.logs

COPY entry.sh /workspace/entry.sh
RUN chmod +x /workspace/entry.sh

ENV TZ Europe/Warsaw
ENV LOG_PATH /workspace/.logs
ENV PID_FILE application.pid

COPY *.jar /workspace/

ENTRYPOINT /workspace/entry.sh
