services:

    proton-mail-export-to-gmail:
      image: ghcr.io/sigmalko/proton-mail-export-to-gmail:${IMG_VERSION_PROTON_MAIL_EXPORT_TO_GMAIL}
      restart: unless-stopped   
      environment:
        SERVER_PORT: 8080
        SWAGGER_SERVER_PUBLIC_URL: ${SWAGGER_SERVER_PUBLIC_URL:-https://github.com/sigmalko/proton-mail-export-to-gmail}
        PROTONMAIL_EXPORT_DATABASE_FILE_PATH: /workspace/.data/h2-database/proton-mail-export-to-gmail
        EML_READER_ENABLED: false
        EML_READER_DIRECTORY: /workspace/.data/proton-emls
        GMAIL_IMAP_FETCH_ENABLED: true
        GMAIL_IMAP_HOST: imap.gmail.com
        GMAIL_IMAP_PORT: 993
        GMAIL_IMAP_SSL_ENABLED: true
        GMAIL_IMAP_USERNAME: ${GMAIL_IMAP_USERNAME:-}
        GMAIL_IMAP_PASSWORD: ${GMAIL_IMAP_PASSWORD:-}
        GMAIL_IMAP_WINDOW_SIZE: ${GMAIL_IMAP_WINDOW_SIZE:-50}
      volumes:
        - type: bind
          source: ${HOST_PROTON_EXPORT_DATABASE_H2_DIR:-.tmp/h2-database}
          target: /workspace/.data/h2-database
          bind:
            create_host_path: true
        - type: bind
          source: ${HOST_PROTON_EMLS_DIR:-.tmp/proton-emls}
          target: /workspace/.data/proton-emls
          bind:
            create_host_path: true       
        - type: bind
          source: ${HOST_PROTON_LOGS_DIR:-.tmp/proton-logs}
          target: /workspace/.logs
          bind:
            create_host_path: true              
      ports:
        - 8080:8080
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s

 
