spring:
    application:
        name: proton-mail-export-to-gmail
    servlet:
        encoding:
            charset: UTF-8
            force-request: true
            force-response: true
            enabled: true
    datasource:
        url: jdbc:h2:file:${protonmail-export.database.file-path};AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password: ""
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    pid:
        fail-on-write-error: true
        file: app.pid
        
logging.config: classpath:logback-dev.xml

swagger.server.public.url: ${SWAGGER_SERVER_PUBLIC_URL:https://github.com/sigmalko/proton-mail-export-to-gmail}

protonmail-export:
  database:
    file-path: ${PROTONMAIL_EXPORT_DATABASE_FILE_PATH:${user.home}/.protonmail-export/database/protonmail-export}

eml:
  reader:
    enabled: ${EML_READER_ENABLED:false}
    directory: ${EML_READER_DIRECTORY:}

gmail:
  imap:
    fetch-enabled: ${GMAIL_IMAP_FETCH_ENABLED:false}
    host: ${GMAIL_IMAP_HOST:imap.gmail.com}
    port: ${GMAIL_IMAP_PORT:993}
    ssl-enabled: ${GMAIL_IMAP_SSL_ENABLED:true}
    username: ${GMAIL_IMAP_USERNAME:}
    password: ${GMAIL_IMAP_PASSWORD:}
    message-limit: ${GMAIL_IMAP_MESSAGE_LIMIT:50}
server:
  port: ${SERVER_PORT:8080}

springdoc:
  use-management-port: false
  api-docs:
    path: /openapi.json
    version: OPENAPI_3_1
    enabled: true
  remove-broken-reference-definitions: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  
server.forward-headers-strategy: framework

---
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
