name: export-to-gmail-docker

on:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/export-to-gmail-docker.yml'
      - 'modules/export-to-gmail-docker/**'
  workflow_call:

env:
  IMAGE_NAME: proton-mail-export-to-gmail
  TAG_VERSION_PREFIX: v1.
  DOCKERFILE_DIRECTORY_PATH: modules/export-to-gmail-docker
  JDK_VERSION: 21

jobs:

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false

      - name: Set padded Docker tag
        id: set_tag
        run: |
          PADDED=$(printf "%03d" ${{ github.run_number }})
          echo "docker_tag=${{ env.TAG_VERSION_PREFIX }}$PADDED" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DOCKERFILE_DIRECTORY_PATH }}
          file: ${{ env.DOCKERFILE_DIRECTORY_PATH }}/Dockerfile-tag
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.docker_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DOCKER_TAG_VERSION=${{ steps.set_tag.outputs.docker_tag }}
            GITHUB_RUN_NUMBER=${{ github.run_number }}