name: export-to-gmail
run-name: ${{ github.workflow }} - ${{ github.event.head_commit.message }}

on:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/export-to-gmail.yml'
      - 'modules/export-to-gmail/pom.xml'
      - 'modules/export-to-gmail/src/**'
      - 'modules/export-to-gmail/Dockerfile-tag'

env:
  JAVA_VERSION: 21
  WORKING_DIRECTORY: modules/export-to-gmail
  MAVEN_USERNAME: ${{ github.actor }}
  MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PACKAGES_URL: https://maven.pkg.github.com/${{ github.repository }}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build and test with Maven
        run: mvn -B -ntp clean verify --file pom.xml
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: export-to-gmail-test-results
          path: ${{ env.WORKING_DIRECTORY }}/target/surefire-reports

      - name: Publish JAR to GitHub Packages
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          mvn -B -ntp deploy -DskipTests --file pom.xml
          -DaltDeploymentRepository=github::${{ env.GITHUB_PACKAGES_URL }}
        working-directory: ${{ env.WORKING_DIRECTORY }}

