name: ops-delete-old-releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ops-delete-old-releases.yml'    

jobs:

  deleting:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List all releases
        run: |
          gh release list --limit 1000 --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete all old releases
        run: |
            gh release list --limit 1000 --repo ${{ github.repository }} --json tagName -q '.[].tagName' | tail -n +2 | while read tag; do
              echo "Deleting release: $tag"
              gh release delete "$tag" -y --repo ${{ github.repository }}
            done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}