name: ops-deploy

on:

  workflow_dispatch:
    inputs:
      docker_image_name:
        description: Docker image to deploy
        required: true
        type: string
        default: proton-mail-export-to-gmail
      docker_tag:
        description: Docker tag to deploy
        required: true
        type: string


env:
  REM_IMG_VER_NAME: IMG_VERSION_PROTON_MAIL_EXPORT_TO_GMAIL

jobs:

  deploying:
    runs-on: ubuntu-latest
    environment: ovh-deploy   
    timeout-minutes: 5

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show informations about release
        run: |
          echo "SIG GHACTION_DEP_NAME : "${{ vars.GHACTION_DEP_NAME }}
          echo "New Docker image 3: ${{ github.repository }}"
          echo "New Docker image 4: ${{ github.ref_name }}"
          echo "New Docker image 5: ${{ github.event_name }}"
          echo "New Docker image 6: ${{ github.workflow }}"
          echo "Input docker_image_name: ${{ github.event.inputs.docker_image_name }}"
          echo "Input docker_tag: ${{ github.event.inputs.docker_tag }}"
          env          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull & run image on prod env
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 2m
          host: ${{ secrets.GHACTION_DEPLOY_SERVER_HOST }}
          username: ${{ vars.GHACTION_DEPLOY_SERVER_USER }}
          key: ${{ secrets.GHACTION_DEPLOY_SERVER_KEY }}
          port: ${{ vars.GHACTION_DEPLOY_SERVER_PORT }}
          script: |
            cd solution
            ls -al
            docker ps
            docker images
            sed -i '/^'${{ env.REM_IMG_VER_NAME }}'=.*$/d' .env
            echo ${{ env.REM_IMG_VER_NAME }}'='${{ github.event.inputs.docker_tag }} >> .env
            docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.docker_image_name }}:${{ github.event.inputs.docker_tag }}

      - name: Send file docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GHACTION_DEPLOY_SERVER_HOST }}
          username: ${{ vars.GHACTION_DEPLOY_SERVER_USER }}
          key: ${{ secrets.GHACTION_DEPLOY_SERVER_KEY }}
          port: ${{ vars.GHACTION_DEPLOY_SERVER_PORT }}
          source: ./modules/export-to-gmail-docker/docker-compose.yml
          target: /home/ubuntu/solution
          strip_components: 3