name: ops-deploy

on:
  registry_package:
    types: [published]
  workflow_dispatch:
    inputs:
      docker_image_name:
        description: Docker image to deploy
        required: true
        type: string
        default: proton-mail-export-to-gmail
      docker_tag:
        description: Docker tag to deploy
        required: true
        type: string

jobs:

  deploying:
    runs-on: ubuntu-latest
    environment: ovh-deploy   
    timeout-minutes: 5

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show informations about release
        run: |
          echo "SIG GHACTION_DEP_NAME : "${{ vars.GHACTION_DEP_NAME }}
          echo "SIG : github.event.registry_package.name="${{ github.event.registry_package.name }}
          echo "SIG github.event.registry_package.package_version.container_metadata.tag.name="${{ github.event.registry_package.package_version.container_metadata.tag.name }}
          echo "New Docker image 1: ${{ github.event.registry_package.name }}"
          echo "New Docker image 2: ${{ github.event.registry_package.namespace }}"          
          echo "New Docker image 3: ${{ github.repository }}"
          echo "New Docker image 4: ${{ github.ref_name }}"
          echo "New Docker image 5: ${{ github.event_name }}"
          echo "New Docker image 6: ${{ github.workflow }}"
          echo "New Docker image 7: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}"
          echo "Input docker_image_name: ${{ github.event.inputs.docker_image_name }}"
          echo "Input docker_tag: ${{ github.event.inputs.docker_tag }}"
          env          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
